version: '3.5'

services:
  nginx:
    image: nginx:latest
    container_name: reposlisting.nginx
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./app:/app
    depends_on:
      - web
    networks:
      - network
    tty: true


  web:
    image: php:7.4-fpm
    build:
      dockerfile: ../docker/web/Dockerfile
      context: ./app
    container_name: reposlisting.web
    volumes:
      - ./app:/app
      - ./docker/web/docker-php-custom.ini:/usr/local/etc/php/conf.d/docker-php-custom.ini
    working_dir: /app
    networks:
      - network
    tty: true

networks:
  network:
   driver: bridge
 
